### ISSUE TITLE
Phase 1: Initial Repository Setup

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/full-stack-testing#1]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/full-stack-testing/issues/2
- [ ] https://github.com/hashgraph/full-stack-testing/issues/3
- [ ] #7
- [ ] https://github.com/hashgraph/full-stack-testing/issues/37
- [ ] https://github.com/hashgraph/full-stack-testing/issues/65
- [ ] https://github.com/hashgraph/full-stack-testing/issues/110
```
