### ISSUE TITLE
FST Phase 1: Bill of Materials

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/full-stack-testing#116]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/full-stack-testing/issues/117
- [ ] https://github.com/hashgraph/full-stack-testing/issues/118
- [ ] https://github.com/hashgraph/full-stack-testing/issues/120
```
