### ISSUE TITLE
IRS: Setup Gradle Projects

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/full-stack-testing#2]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/full-stack-testing/issues/9
- [ ] https://github.com/hashgraph/full-stack-testing/issues/8
- [ ] https://github.com/hashgraph/full-stack-testing/issues/33
- [ ] https://github.com/hashgraph/full-stack-testing/issues/10
- [ ] https://github.com/hashgraph/full-stack-testing/issues/11
- [ ] https://github.com/hashgraph/full-stack-testing/issues/12
- [ ] https://github.com/hashgraph/full-stack-testing/issues/13
- [ ] https://github.com/hashgraph/full-stack-testing/issues/14
- [ ] https://github.com/hashgraph/full-stack-testing/issues/15
- [ ] https://github.com/hashgraph/full-stack-testing/issues/16
- [ ] https://github.com/hashgraph/full-stack-testing/issues/17
- [ ] https://github.com/hashgraph/full-stack-testing/issues/18
- [ ] https://github.com/hashgraph/full-stack-testing/issues/19
- [ ] https://github.com/hashgraph/full-stack-testing/issues/20
- [ ] https://github.com/hashgraph/full-stack-testing/issues/21
- [ ] https://github.com/hashgraph/full-stack-testing/issues/22
- [ ] https://github.com/hashgraph/full-stack-testing/issues/23
- [ ] https://github.com/hashgraph/full-stack-testing/issues/24
- [ ] https://github.com/hashgraph/full-stack-testing/issues/25
- [ ] https://github.com/hashgraph/full-stack-testing/issues/26
- [ ] https://github.com/hashgraph/full-stack-testing/issues/27
- [ ] https://github.com/hashgraph/full-stack-testing/issues/28
- [ ] https://github.com/hashgraph/full-stack-testing/issues/29
- [ ] https://github.com/hashgraph/full-stack-testing/issues/30
- [ ] https://github.com/hashgraph/full-stack-testing/issues/31
- [ ] https://github.com/hashgraph/full-stack-testing/issues/32
- [ ] https://github.com/hashgraph/full-stack-testing/issues/46
- [ ] https://github.com/hashgraph/full-stack-testing/issues/57
- [ ] https://github.com/hashgraph/full-stack-testing/issues/59
```
