### ISSUE TITLE
Charts[Network Node]: Enhance dev scripts to validate the state and functionality of the sidecar containers

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/full-stack-testing#223]
- Validate appropriate sidecars are deployed and running when enabled (verify both positive and negative case)
- For Open Telemetry, ensure we are getting actual telemetry submitted or processed (for network node and other side cars were telemetry is enabled)
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/full-stack-testing/issues/308
- [ ] https://github.com/hashgraph/full-stack-testing/issues/307
- [ ] https://github.com/hashgraph/full-stack-testing/issues/315
- [ ] https://github.com/hashgraph/full-stack-testing/issues/316
```
