### ISSUE TITLE
IRS: Setup Github Actions

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/full-stack-testing#3]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/full-stack-testing/issues/34
- [ ] https://github.com/hashgraph/full-stack-testing/issues/35
- [ ] #6
- [ ] #5
- [ ] #4
- [ ] https://github.com/hashgraph/full-stack-testing/issues/36
- [ ] https://github.com/hashgraph/full-stack-testing/issues/107
- [ ] https://github.com/hashgraph/full-stack-testing/issues/109
```
