### ISSUE TITLE
Charts[GKE-BUG] GKE Deployment Issues - First Pass

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/full-stack-testing#368]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/full-stack-testing/issues/370
- [ ] https://github.com/hashgraph/full-stack-testing/issues/369
- [ ] https://github.com/hashgraph/full-stack-testing/issues/371
- [ ] https://github.com/hashgraph/full-stack-testing/issues/372
- [ ] https://github.com/hashgraph/full-stack-testing/issues/373
- [ ] https://github.com/hashgraph/full-stack-testing/issues/381
- [ ] https://github.com/hashgraph/full-stack-testing/issues/388
```
