### ISSUE TITLE
CLI: Create FS Network Manager (FSNetMan) CLI

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/full-stack-testing#420]
### Requested Feature
We need a NodeJS CLI to be able to deploy the chart and provision a FST network for local testing.

### Business Need
The ability to have a user friendly tool to manage FST network deployment is super critical to let community developers as well as SwirldsLabs to run their tests on a proper multi-node hedera network without relying on Testnet.

### Additional Context
We need to be able to install the tool using package manager like npm
It needs to allow deploying the network nodes and other optional components using appropriate command line flags

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/full-stack-testing/issues/423
- [ ] https://github.com/hashgraph/full-stack-testing/issues/433
- [ ] https://github.com/hashgraph/full-stack-testing/issues/432
- [ ] https://github.com/hashgraph/full-stack-testing/issues/451
- [ ] https://github.com/hashgraph/full-stack-testing/issues/448
- [ ] https://github.com/hashgraph/full-stack-testing/issues/444
- [ ] https://github.com/hashgraph/full-stack-testing/issues/455
- [ ] https://github.com/hashgraph/full-stack-testing/issues/457
- [ ] https://github.com/hashgraph/full-stack-testing/issues/507
- [ ] https://github.com/hashgraph/full-stack-testing/issues/497
- [ ] https://github.com/hashgraph/full-stack-testing/issues/519
- [ ] https://github.com/hashgraph/full-stack-testing/issues/501
- [ ] https://github.com/hashgraph/full-stack-testing/issues/515
- [ ] https://github.com/hashgraph/full-stack-testing/issues/510
- [ ] https://github.com/hashgraph/full-stack-testing/issues/518
- [ ] https://github.com/hashgraph/full-stack-testing/issues/481
- [ ] https://github.com/hashgraph/full-stack-testing/issues/556
- [ ] https://github.com/hashgraph/full-stack-testing/issues/565
- [ ] https://github.com/hashgraph/full-stack-testing/issues/576
- [ ] https://github.com/hashgraph/full-stack-testing/issues/619
- [ ] https://github.com/hashgraph/full-stack-testing/issues/622
- [ ] https://github.com/hashgraph/full-stack-testing/issues/511
- [ ] https://github.com/hashgraph/full-stack-testing/issues/512
- [ ] https://github.com/hashgraph/full-stack-testing/issues/582
- [ ] https://github.com/hashgraph/full-stack-testing/issues/564
- [ ] https://github.com/hashgraph/full-stack-testing/issues/660
- [ ] https://github.com/hashgraph/full-stack-testing/issues/605
- [ ] https://github.com/hashgraph/full-stack-testing/issues/561
- [ ] https://github.com/hashgraph/full-stack-testing/issues/508
- [ ] https://github.com/hashgraph/full-stack-testing/issues/509
- [ ] https://github.com/hashgraph/full-stack-testing/issues/514
- [ ] https://github.com/hashgraph/full-stack-testing/issues/516
- [ ] https://github.com/hashgraph/full-stack-testing/issues/517
- [ ] https://github.com/hashgraph/full-stack-testing/issues/652
- [ ] https://github.com/hashgraph/full-stack-testing/issues/657
- [ ] https://github.com/hashgraph/full-stack-testing/issues/543
- [ ] https://github.com/hashgraph/full-stack-testing/issues/456
- [ ] https://github.com/hashgraph/full-stack-testing/issues/461
- [ ] https://github.com/hashgraph/full-stack-testing/issues/668
- [ ] https://github.com/hashgraph/full-stack-testing/issues/669
- [ ] https://github.com/hashgraph/full-stack-testing/issues/670
- [ ] https://github.com/hashgraph/full-stack-testing/issues/718
- [ ] https://github.com/hashgraph/full-stack-testing/issues/722
- [ ] https://github.com/hashgraph/full-stack-testing/issues/734
- [ ] https://github.com/hashgraph/full-stack-testing/issues/739
- [ ] https://github.com/hashgraph/full-stack-testing/issues/741
- [ ] https://github.com/hashgraph/full-stack-testing/issues/748
- [ ] https://github.com/hashgraph/full-stack-testing/issues/752
- [ ] https://github.com/hashgraph/full-stack-testing/issues/765
```

**Comment by leninmehedy** [comment]
Need to be able to expose ports (as discussed with @qnswirlds )

```
Download CLI using `npm i fullstack-network-manager`
- Expose explorer by running `fsnetman expose hedera-explorer <LOCAL_PORT>`
- Expose node0 by running `fsnetman expose node -n node0 <LOCAL_PORT>`
````
