### ISSUE TITLE
CLI[Node]: Implement node setup, start and stop commands

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/full-stack-testing#455]
We need to use `direct-install` method to upload the JARs and setup node.
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/full-stack-testing/issues/469
- [ ] https://github.com/hashgraph/full-stack-testing/issues/470
- [ ] https://github.com/hashgraph/full-stack-testing/issues/471
- [ ] https://github.com/hashgraph/full-stack-testing/issues/472
- [ ] https://github.com/hashgraph/full-stack-testing/issues/489
- [ ] https://github.com/hashgraph/full-stack-testing/issues/500
```

**Comment by leninmehedy** [comment]
Done
