### ISSUE TITLE
CLI[Test]: Write e2e tests to test functionalities

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/full-stack-testing#516]
Objective of this task is to ensure functionalities using e2e tests.

```[tasklist]
### Tasks
- [ ] CLI[E2E] Implement e2e test for cluster command
- [ ] CLI[E2E] Implement e2e test for chart command
- [ ] CLI[E2E] Implement e2e test for node command
```
