### ISSUE TITLE
CLI[Test]: Improve test coverage

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/full-stack-testing#517]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/full-stack-testing/issues/546
- [ ] https://github.com/hashgraph/full-stack-testing/issues/547
- [ ] https://github.com/hashgraph/full-stack-testing/issues/548
- [ ] https://github.com/hashgraph/full-stack-testing/issues/549
- [ ] https://github.com/hashgraph/full-stack-testing/issues/550
- [ ] https://github.com/hashgraph/full-stack-testing/issues/551
- [ ] https://github.com/hashgraph/full-stack-testing/issues/552
- [ ] https://github.com/hashgraph/full-stack-testing/issues/553
- [ ] https://github.com/hashgraph/full-stack-testing/issues/554
- [ ] https://github.com/hashgraph/full-stack-testing/issues/555
- [ ] https://github.com/hashgraph/full-stack-testing/issues/545
- [ ] https://github.com/hashgraph/solo/issues/36
```
