### ISSUE TITLE
CLI[UX]: Improve CLI User Experience

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/full-stack-testing#518]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/full-stack-testing/issues/583
- [ ] https://github.com/hashgraph/full-stack-testing/issues/584
- [ ] https://github.com/hashgraph/full-stack-testing/issues/590
- [ ] https://github.com/hashgraph/full-stack-testing/issues/588
- [ ] https://github.com/hashgraph/full-stack-testing/issues/589
- [ ] https://github.com/hashgraph/full-stack-testing/issues/596
```
