### ISSUE TITLE
FST Phase 1: Mock Example Unit Test for Signed State Testing Tool

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/full-stack-testing#90]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/full-stack-testing/issues/93
- [ ] https://github.com/hashgraph/full-stack-testing/issues/94
- [ ] https://github.com/hashgraph/full-stack-testing/issues/95
- [ ] https://github.com/hashgraph/full-stack-testing/issues/96
- [ ] https://github.com/hashgraph/full-stack-testing/issues/97
- [ ] https://github.com/hashgraph/full-stack-testing/issues/98
- [ ] https://github.com/hashgraph/full-stack-testing/issues/99
- [ ] https://github.com/hashgraph/full-stack-testing/issues/100
- [ ] https://github.com/hashgraph/full-stack-testing/issues/101
- [ ] https://github.com/hashgraph/full-stack-testing/issues/102
```
