### ISSUE TITLE
GI: move FST Helm charts to their own repo

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/full-stack-testing#907]
This will be moved to hashgraph/solo-charts.

Included in this will be setting up the repo with everything needed (include things not listed or update this list, each item can be converted to an issue or altered as needed):

```[tasklist]
### Tasks
- [x] GitHub workflows
- [x] GitHub CODEOWNERS file
- [x] dependabot setup
- [x] GitHub Settings / Rules / Rulesets
- [x] GitHub secrets
- [x] migrating charts directory
- [x] GitHub Pages for deploying Helm Charts to
- [x] create GitHub Issue to update Solo to point to the new Helm Charts location
- [x] remove charts directory from FST repo
- [x] remove Helm Chart related items from GitHub FST workflows
- [x] update any references in `fullstack-core`, `fullstack-examples`, and `fullstack-gradle-plugin` directories to the helm charts or docker containers that were migrated
- [x] rebrand the charts to be solo instead of fullstack testing
- [x] remove Docker Containers files and directories from FST repo
- [x] remove Docker container related items from GitHub FST workflows
```
