### ISSUE TITLE
UT Mock: Required Infrastructure API

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/full-stack-testing#93]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/full-stack-testing/issues/301
- [ ] https://github.com/hashgraph/full-stack-testing/issues/385
- [ ] https://github.com/hashgraph/full-stack-testing/issues/395
```
